#ifndef REDENNETWORKLIB_GLOBAL_H
#define REDENNETWORKLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REDENNETWORKLIB_LIBRARY)
#  define REDENNETWORKLIB_EXPORT Q_DECL_EXPORT
#else
#  define REDENNETWORKLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // REDENNETWORKLIB_GLOBAL_H
